server:
  port: 8080
  servlet:
    context-path: /identity
spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/spring_boot"
    username: root
    password: NhanThien24
  data:
    redis:
      host: "localhost"
      port: 6379
  jpa:
    hibernate:
      ddl-auto: update
jwt:
  signerKey: "eSNwp01GDWLGaME9rWUyq57isilK6b2v"
  valid-duration: 20 #seconds
  refreshable-duration: 120 #seconds